### ISSUE TITLE
pytest watch seems to fail when pyproject.toml is used as a config file

### ISSUE THREAD

**Issue by max-sixty** [joeyespo/pytest-watch#114]
When pytest config is stored in `pyproject.toml`:

```
Traceback (most recent call last):
  File "/Users/maximilian/Library/Caches/pypoetry/virtualenvs/n-cyukv0jK-py3.8/bin/ptw", line 8, in <module>
    sys.exit(main())
  File "/Users/maximilian/Library/Caches/pypoetry/virtualenvs/n-cyukv0jK-py3.8/lib/python3.8/site-packages/pytest_watch/command.py", line 83, in main
    if not merge_config(args, pytest_args, verbose=args['--verbose']):
  File "/Users/maximilian/Library/Caches/pypoetry/virtualenvs/n-cyukv0jK-py3.8/lib/python3.8/site-packages/pytest_watch/config.py", line 95, in merge_config
    config.read(config_path)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/Users/maximilian/workspace/n/pyproject.toml'
	[line 59]: ']\n'
```

This works when the pytest config in `pyproject.toml` is removed

**Comment by Kreeg** [comment]
any updates?

**Comment by satheler** [comment]
Same problem here.

**Comment by Jufik** [comment]
Faced the same issue and investigated my `pyproject.toml`

anytime you have
```
variable=[
    ....
]
```
I change to (note the 4 spaces)
```
variable=[
    ....
    ]
``` 

PTW works like a charm

**Comment by abdul-hamid-achik** [comment]
folks how can one simple mortal format a file in a way where this does not happen but you keep your pytest config on your pyproject.toml?

**Comment by abdul-hamid-achik** [comment]
btw moving pytest configuration form pyproject.toml to pytest.ini did the trick but I would prefer to not have extra config files

**Comment by ketozhang** [comment]
As we can see in the trace, this tool only implements parsing using the configparser — it assumes pytest config are only ini files. What I see the next steps are for pytest-watch to stop bootstrapping off of `pytest.config` and start handling their own parsing of `pytest.ini`, `pyproject.toml`, and any legacy config files.

@joeyespo Any interest of accepting contributions to this?

**Comment by olzhasar** [comment]
For anyone who is looking for a working and maintained alternative to `pytest-watch`:
https://github.com/olzhasar/pytest-watcher
