### ISSUE TITLE
Error with `--collect-only` gets not displayed verbatim

### ISSUE THREAD

**Issue by blueyed** [joeyespo/pytest-watch#59]
The traceback after `--collect-only` failed is not the same as with calling `py.test --collect-only` directly:

With `ptw project-dir`:

```
Error: Could not run --collect-only to find the pytest config file. Trying again without silencing stdout...
Traceback (most recent call last):
  File "…/pyenv/project/bin/ptw", line 9, in <module>
    load_entry_point('pytest-watch', 'console_scripts', 'ptw')()
  File "…/pytest-watch/pytest_watch/command.py", line 83, in main
    if not merge_config(args, pytest_args, verbose=args['--verbose']):
  File "…/pytest-watch/pytest_watch/config.py", line 86, in merge_config
    config_path = _collect_config(pytest_args, silent)
  File "…/pytest-watch/pytest_watch/config.py", line 78, in _collect_config
    return _run_pytest_collect(pytest_args)
  File "…/pytest-watch/pytest_watch/config.py", line 52, in _run_pytest_collect
    exit_code = pytest.main(argv, plugins=[collect_config_plugin])
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 118, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 861, in pytest_cmdline_parse
    self.parse(args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 966, in parse
    self._preparse(args, addopts=addopts)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 937, in _preparse
    args=args, parser=self._parser)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
    return call_outcome.get_result()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "…/pyenv/project/lib/python3.5/site-packages/pytest_django/plugin.py", line 238, in pytest_load_initial_conftests
    _setup_django()
  File "…/pyenv/project/lib/python3.5/site-packages/pytest_django/plugin.py", line 134, in _setup_django
    django.setup()
  File "…/django/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "…/django/django/apps/registry.py", line 78, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
```

With `py.test --collect-only project-dir`:
```
Traceback (most recent call last):
  File "…/pyenv/project/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 118, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 861, in pytest_cmdline_parse
    self.parse(args)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 966, in parse
    self._preparse(args, addopts=addopts)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/config.py", line 937, in _preparse
    args=args, parser=self._parser)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
    return call_outcome.get_result()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "…/pyenv/project/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "…/pyenv/project/lib/python3.5/site-packages/pytest_django/plugin.py", line 238, in pytest_load_initial_conftests
    _setup_django()
  File "…/pyenv/project/lib/python3.5/site-packages/pytest_django/plugin.py", line 134, in _setup_django
    django.setup()
  File "…/django/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "…/django/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "…/django/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "…/pyenv/project/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 764, in get_code
  File "<frozen importlib._bootstrap_external>", line 724, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "…/app/models.py", line 2082
    import bpdb
         ^
SyntaxError: invalid syntax
```

**Comment by blueyed** [comment]
This seems to be caused by "pytest-django" setting up Django twice.

I've seen a similar issue now again, which seems to be caused by a `TypeError` during loading the settings, and when run again, it complains about `django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`.

I think that pytest-watch should rather capture the output and display it in case of errors, instead of running pytest's main method again?!  And/or it would need to be separated like the main run (after collection).

**Comment by blueyed** [comment]
For Python 3.4 there is `redirect_stdout` / `redirect_stderr`:
https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout

**Comment by blueyed** [comment]
We could use https://pypi.python.org/pypi/contextlib2 to have it for older Python versions and/or implement/copy it ourselves.
