### ISSUE TITLE
Installation fails when using Windows 10, Python 3.6 and Pipenv 9.0.3

### ISSUE THREAD

**Issue by juhamust** [joeyespo/pytest-watch#84]
Tried installing the package using Windows 10, Python 3.6 and Pipenv 9.0.3 but failed because of the following error:  

```python
Error:  An error occurred while installing pytest-watch!
Exception:
Traceback (most recent call last):
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\pip\locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "c:\users\jklmustoju\.virtualenvs\projectx-oczq1phh\lib\site-packages\setuptools\command\install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "c:\users\jklmustoju\appdata\local\programs\python\python36\Lib\distutils\command\install.py", line 346, in finalize_options
    'userbase', 'usersite')
  File "c:\users\jklmustoju\appdata\local\programs\python\python36\Lib\distutils\command\install.py", line 487, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
  File "c:\users\jklmustoju\appdata\local\programs\python\python36\Lib\distutils\util.py", line 125, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/Lib/site-packages' cannot be absolute
```

**Comment by juhamust** [comment]
Duh! Finally resolved the issue - and it was causing same error pretty much in every corner :( Removing the following lines (that was accidentally added at some point) from `setup.cfg` fixed the issue:
```patch
- [install]
- prefix=
```

**Comment by joeyespo** [comment]
Oh excellent, thanks for closing with an explanation! 😃 

If you (or anyone reading) can think of how pytest-watch can help diagnose / prevent this kind of error in the future, feel free to comment here with ideas.
